package bje.buildtools.dependency.explorer.license;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.TreeMap;

public class WriteCofn {
    private static final String GPL_2_0_WITH_CLASSPATH_EXCEPTION = "GPL-2.0-with-classpath-exception";

    private static final Map<String, List<String>> map = new TreeMap<>();

    public static void main(final String[] args) {
        put("BSD Zero Clause License", "0BSD");
        put("Attribution Assurance License", "AAL");
        put("Academic Free License v1.1", "AFL-1.1");
        put("Academic Free License v1.2", "AFL-1.2");
        put("Academic Free License v2.0", "AFL-2.0");
        put("Academic Free License v2.1", "AFL-2.1");
        put("Academic Free License v3.0", "AFL-3.0");
        put("GNU Affero General Public License v3.0", "AGPL-3.0");
        put("GNU Affero General Public License v3.0 only", "AGPL-3.0");
        put("GNU Affero General Public License v3.0 or later", "AGPL-3.0+");
        put("Apache License 1.0", "Apache-1.0");
        put("Apache License 1.1", "Apache-1.1");
        put("Apache License 2.0", "Apache-2.0");
        put("Adaptive Public License 1.0", "APL-1.0");
        put("Apple Public Source License 1.0", "APSL-1.0");
        put("Apple Public Source License 1.1", "APSL-1.1");
        put("Apple Public Source License 1.2", "APSL-1.2");
        put("Apple Public Source License 2.0", "APSL-2.0");
        put("Artistic License 1.0", "Artistic-1.0");
        put("Artistic License 1.0 w/clause 8", "Artistic-1.0-cl8");
        put("Artistic License 1.0 (Perl)", "Artistic-1.0-Perl");
        put("Artistic License 2.0", "Artistic-2.0");
        put("BitTorrent Open Source License v1.1", "BitTorrent-1.1");
        put("Blue Oak Model License 1.0.0", "BlueOak-1.0.0");
        put("BSD 1-Clause License", "BSD-1-Clause");
        put("BSD 2-Clause \"Simplified\" License", "BSD-2-Clause");
        put("BSD-2-Clause Plus Patent License", "BSD-2-Clause-Patent");
        put("BSD 3-Clause \"New\" or \"Revised\" License", "BSD-3-Clause");
        put("BSD 3-Clause Clear License", "BSD-3-Clause-Clear");
        put("Lawrence Berkeley National Labs BSD variant license", "BSD-3-Clause-LBNL");
        put("BSD 4-Clause \"Original\" or \"Old\" License", "BSD-4-Clause");
        put("Boost Software License 1.0", "BSL-1.0");
        put("Cryptographic Autonomy License 1.0", "CAL-1.0");
        put("Cryptographic Autonomy License 1.0 (Combined Work Exception)", "CAL-1.0-Combined-Work-Exception");
        put("Computer Associates Trusted Open Source License 1.1", "CATOSL-1.1");
        put("Creative Commons Attribution 4.0 International", "CC-BY-4.0");
        put("Creative Commons Attribution Share Alike 4.0 International", "CC-BY-SA-4.0");
        put("Creative Commons Zero v1.0 Universal", "CC0-1.0");
        put("Common Development and Distribution License 1.0", "CDDL-1.0");
        put("CeCILL Free Software License Agreement v2.0", "CECILL-2.0");
        put("CeCILL Free Software License Agreement v2.1", "CECILL-2.1");
        put("CeCILL-B Free Software License Agreement", "CECILL-B");
        put("CeCILL-C Free Software License Agreement", "CECILL-C");
        put("CERN Open Hardware Licence Version 2 - Permissive", "CERN-OHL-P-2.0");
        put("CERN Open Hardware Licence Version 2 - Strongly Reciprocal", "CERN-OHL-S-2.0");
        put("CERN Open Hardware Licence Version 2 - Weakly Reciprocal", "CERN-OHL-W-2.0");
        put("Clarified Artistic License", "ClArtistic");
        put("CNRI Python License", "CNRI-Python");
        put("Condor Public License v1.1", "Condor-1.1");
        put("Common Public Attribution License 1.0", "CPAL-1.0");
        put("Common Public License 1.0", "CPL-1.0");
        put("CUA Office Public License v1.0", "CUA-OPL-1.0");
        put("Educational Community License v1.0", "ECL-1.0");
        put("Educational Community License v2.0", "ECL-2.0");
        put("Eiffel Forum License v1.0", "EFL-1.0");
        put("Eiffel Forum License v2.0", "EFL-2.0");
        put("Entessa Public License v1.0", "Entessa");
        put("Eclipse Public License 1.0", "EPL-1.0");
        put("Eclipse Public License 2.0", "EPL-2.0");
        put("EU DataGrid Software License", "EUDatagrid");
        put("European Union Public License 1.1", "EUPL-1.1");
        put("European Union Public License 1.2", "EUPL-1.2");
        put("Fair License", "Fair");
        put("Frameworx Open License 1.0", "Frameworx-1.0");
        put("FSF All Permissive License", "FSFAP");
        put("Freetype Project License", "FTL");
        put("GNU Free Documentation License v1.1", "GFDL-1.1");
        put("GNU Free Documentation License v1.1 only", "GFDL-1.1");
        put("GNU Free Documentation License v1.1 or later", "GFDL-1.1+");
        put("GNU Free Documentation License v1.2", "GFDL-1.2");
        put("GNU Free Documentation License v1.2 only", "GFDL-1.2");
        put("GNU Free Documentation License v1.2 or later", "GFDL-1.2+");
        put("GNU Free Documentation License v1.3", "GFDL-1.3");
        put("GNU Free Documentation License v1.3 only", "GFDL-1.3");
        put("GNU Free Documentation License v1.3 or later", "GFDL-1.3+");
        put("gnuplot License", "gnuplot");
        put("GNU General Public License v2.0", "GPL-2.0");
        put("GNU General Public License v2.0 only", "GPL-2.0");
        put("GNU General Public License v2.0 or later", "GPL-2.0+");
        put("GNU General Public License v3.0", "GPL-3.0");
        put("GNU General Public License v3.0 only", "GPL-3.0");
        put("GNU General Public License v3.0 or later", "GPL-3.0+");
        put("Historical Permission Notice and Disclaimer", "HPND");
        put("ICU License", "ICU");
        put("Independent JPEG Group License", "IJG");
        put("iMatix Standard Function Library Agreement", "iMatix");
        put("Imlib2 License", "Imlib2");
        put("Intel Open Source License", "Intel");
        put("IPA Font License", "IPA");
        put("IBM Public License v1.0", "IPL-1.0");
        put("ISC License", "ISC");
        put("Jam License", "Jam");
        put("GNU Library General Public License v2", "LGPL-2.0");
        put("GNU Library General Public License v2 only", "LGPL-2.0");
        put("GNU Library General Public License v2 or later", "LGPL-2.0+");
        put("GNU Lesser General Public License v2.1", "LGPL-2.1");
        put("GNU Lesser General Public License v2.1 only", "LGPL-2.1");
        put("GNU Lesser General Public License v2.1 or later", "LGPL-2.1+");
        put("GNU Lesser General Public License v3.0", "LGPL-3.0");
        put("GNU Lesser General Public License v3.0 only", "LGPL-3.0");
        put("GNU Lesser General Public License v3.0 or later", "LGPL-3.0+");
        put("Licence Libre du Québec – Permissive version 1.1", "LiLiQ-P-1.1");
        put("Licence Libre du Québec – Réciprocité version 1.1", "LiLiQ-R-1.1");
        put("Licence Libre du Québec – Réciprocité forte version 1.1", "LiLiQ-Rplus-1.1");
        put("Lucent Public License Version 1.0", "LPL-1.0");
        put("Lucent Public License v1.02", "LPL-1.02");
        put("LaTeX Project Public License v1.2", "LPPL-1.2");
        put("LaTeX Project Public License v1.3a", "LPPL-1.3a");
        put("LaTeX Project Public License v1.3c", "LPPL-1.3c");
        put("The MirOS Licence", "MirOS");
        put("MIT License", "MIT");
        put("MIT No Attribution", "MIT-0");
        put("MIT License Modern Variant", "MIT-Modern-Variant");
        put("Motosoto License", "Motosoto");
        put("Mozilla Public License 1.0", "MPL-1.0");
        put("Mozilla Public License 1.1", "MPL-1.1");
        put("Mozilla Public License 2.0", "MPL-2.0");
        put("Mozilla Public License 2.0 (no copyleft exception)", "MPL-2.0-no-copyleft-exception");
        put("Microsoft Public License", "MS-PL");
        put("Microsoft Reciprocal License", "MS-RL");
        put("Mulan Permissive Software License, Version 2", "MulanPSL-2.0");
        put("Multics License", "Multics");
        put("NASA Open Source Agreement 1.3", "NASA-1.3");
        put("Naumen Public License", "Naumen");
        put("University of Illinois/NCSA Open Source License", "NCSA");
        put("Nethack General Public License", "NGPL");
        put("Nokia Open Source License", "Nokia");
        put("Netizen Open Source License", "NOSL");
        put("Netscape Public License v1.0", "NPL-1.0");
        put("Netscape Public License v1.1", "NPL-1.1");
        put("Non-Profit Open Software License 3.0", "NPOSL-3.0");
        put("NTP License", "NTP");
        put("OCLC Research Public License 2.0", "OCLC-2.0");
        put("Open Data Commons Open Database License v1.0", "ODbL-1.0");
        put("SIL Open Font License 1.0", "OFL-1.0");
        put("SIL Open Font License 1.1", "OFL-1.1");
        put("SIL Open Font License 1.1 with no Reserved Font Name", "OFL-1.1-no-RFN");
        put("SIL Open Font License 1.1 with Reserved Font Name", "OFL-1.1-RFN");
        put("Open Group Test Suite License", "OGTSL");
        put("Open LDAP Public License v2.3", "OLDAP-2.3");
        put("Open LDAP Public License v2.7", "OLDAP-2.7");
        put("Open LDAP Public License v2.8", "OLDAP-2.8");
        put("Open Logistics Foundation License Version 1.3", "OLFL-1.3");
        put("OpenSSL License", "OpenSSL");
        put("OSET Public License version 2.1", "OSET-PL-2.1");
        put("Open Software License 1.0", "OSL-1.0");
        put("Open Software License 1.1", "OSL-1.1");
        put("Open Software License 2.0", "OSL-2.0");
        put("Open Software License 2.1", "OSL-2.1");
        put("Open Software License 3.0", "OSL-3.0");
        put("PHP License v3.0 ", "PHP-3.0");
        put("PHP License v3.01", "PHP-3.01");
        put("PostgreSQL License", "PostgreSQL");
        put("Python License 2.0", "Python-2.0");
        put("Q Public License 1.0", "QPL-1.0");
        put("Reciprocal Public License 1.1", "RPL-1.1");
        put("Reciprocal Public License 1.5", "RPL-1.5");
        put("RealNetworks Public Source License v1.0", "RPSL-1.0");
        put("Ricoh Source Code Public License", "RSCPL");
        put("Ruby License", "Ruby");
        put("SGI Free Software License B v2.0", "SGI-B-2.0");
        put("Simple Public License 2.0", "SimPL-2.0");
        put("Sun Industry Standards Source License v1.1", "SISSL");
        put("Sleepycat License", "Sleepycat");
        put("Standard ML of New Jersey License", "SMLNJ");
        put("Sun Public License v1.0", "SPL-1.0");
        put("Upstream Compatibility License v1.0", "UCL-1.0");
        put("Unicode License v3", "Unicode-3.0");
        put("Unicode License Agreement - Data Files and Software (2016)", "Unicode-DFS-2016");
        put("The Unlicense", "Unlicense");
        put("Universal Permissive License v1.0", "UPL-1.0");
        put("Vim License", "Vim");
        put("Vovida Software License v1.0", "VSL-1.0");
        put("W3C Software Notice and License (2002-12-31)", "W3C");
        put("W3C Software Notice and Document License (2015-05-13)", "W3C-20150513");
        put("Sybase Open Watcom Public License 1.0", "Watcom-1.0");
        put("Do What The F*ck You Want To Public License", "WTFPL");
        put("X11 License", "X11");
        put("XFree86 License 1.1", "XFree86-1.1");
        put("xinetd License", "xinetd");
        put("X.Net License", "Xnet");
        put("Yahoo! Public License v1.1", "YPL-1.1");
        put("Zend License v2.0", "Zend-2.0");
        put("Zimbra Public License v1.3", "Zimbra-1.3");
        put("zlib License", "Zlib");
        put("Zope Public License 2.0", "ZPL-2.0");
        put("Zope Public License 2.1", "ZPL-2.1");
        put("Affero General Public License v1.0", "AGPL-1.0");
        put("BSD 2-Clause FreeBSD License", "BSD-2-Clause-FreeBSD");
        put("BSD 2-Clause NetBSD License", "BSD-2-Clause-NetBSD");
        put("GNU General Public License v1.0", "GPL-1.0");
        put("GNU General Public License v1.0 only", "GPL-1.0");
        put("GNU General Public License v1.0 or later", "GPL-1.0+");
        put("GNU General Public License v2.0 w/Autoconf exception", "GPL-2.0-with-autoconf-exception");
        put("GNU General Public License v2.0 w/Bison exception", "GPL-2.0-with-bison-exception");
        put("GNU General Public License v2.0 w/Classpath exception", GPL_2_0_WITH_CLASSPATH_EXCEPTION);
        put("EPL 2.0", "EPL-2.0");
        put("GPL2 w/ CPE", GPL_2_0_WITH_CLASSPATH_EXCEPTION);
        put("GNU General Public License v2.0 w/Font exception", "GPL-2.0-with-font-exception");
        put("GNU General Public License v2.0 w/GCC Runtime Library exception", "GPL-2.0-with-GCC-exception");
        put("GNU General Public License v3.0 w/Autoconf exception", "GPL-3.0-with-autoconf-exception");
        put("GNU General Public License v3.0 w/GCC Runtime Library exception", "GPL-3.0-with-GCC-exception");
        put("CDDL + GPLv2 with classpath exception", "CDDL-1.0", GPL_2_0_WITH_CLASSPATH_EXCEPTION);
        put("CDDLGPLv2+CE", "CDDL-1.0", GPL_2_0_WITH_CLASSPATH_EXCEPTION);

        print();
    }

    private static void print() {
        System.out.println("<licenseIdentitites>");
        for (final Entry<String, List<String>> e : map.entrySet()) {
            System.out.println("    <licenseIdentity>");
            System.out.print("        <name>");
            System.out.print(e.getKey());
            System.out.println("</name>");
            System.out.println("        <matching>");
            for (final String m : e.getValue()) {
                System.out.print("            <match>");
                System.out.print(m);
                System.out.println("</match>");
            }
            System.out.println("        </matching>");
            System.out.println("    </licenseIdentity>");
        }
        System.out.println("</licenseIdentitites>");
    }

    public static void put(final String match, final String... ids) {
        for (final String id : ids) {
            final var matchs = map.computeIfAbsent(id, n -> new ArrayList<>());
            matchs.add(match);
        }
    }

}
